version: '2'
services:
  db:
   image: mysql:5.7
   container_name: mysql_database
   volumes:
    - db_data:/var/lib/mysql
   restart: always
          
   environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: test

  wordpress:
   depends_on:
    - db
   image: wordpress
   container_name: wordpress
   volumes: 
    - wpfiles:/var/lib/html
   ports: 
    - "8000:80"

   restart: always 
   environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: test

volumes: 
 wpfiles:
 db_data:
